### ISSUE TITLE
Code is untested

### ISSUE THREAD

**Issue by WrongBit** [pihi/scram#2]
It fails on the very first iteration:

PANIC! System.FormatException: One of the identified items was in an invalid format.
   at Scram.ScramAttribute.Parse(String attribute) in .....\Scram.Core\ScramAttribute.cs:line 28

Code tries to "spit" name=value pair, while got string "n".

**Comment by ihildebrandt** [comment]
This was for a project that never got off the ground. This code is not finished and probably never will be. Feel free to fork it and use it as a jumping off point, but at this point I don't know if I will ever revisit it.
